resource_group_name             = "st6.5-sda-terraform"                   #Replace It   
location                        = "France Central"                        #You Can Replace It, ((((please keep it)))
subscription_id                 = ""  #Add you Azure subscription id      #Replace It
tenant_id                       = ""  #Add you Azure tenant_id            #Replace It
vmss_name                       = "sda-st.6.5vmss"                        #Replace It
vm_name                         = "sda-stage6.5-vm"                       #Replace It
host_name                       = "azureuser"                             #You Can Replace It, ((((better keep it)))
vm_size                         = "Standard_F1s"                          #You Can Replace It, ((((better keep it)))
vnet_name                       = "st6.5-sda-vnet"                        #You Can Replace It, It's up to you
subnet_name                     = "default-st6.5-sda"                     #You Can Replace It, It's up to you
nsg_name_chroma                 = "st6.5-vmss-sda-nsg"                    #You Can Replace It, It's up to you
nsg_name_vmss                   = "st6.5-chroma-sda-nsg"                  #You Can Replace It, It's up to you
public_ip_name                  = "st6.5-sda-public-ip"                   #You Can Replace It, It's up to you
nic_name                        = "st6.5-sda-nic"                         #You Can Replace It, It's up to you
disk_name                       = "st6.5-sda-disk"                        #You Can Replace It, It's up to you
disk_size_gb                    = 30                                      #You Can Replace It (Dooon't touch It)
azure_storage_account_name      = "sda61projstaccount"                    #Replace It
azure_storage_container         = "pdf"                                   #You Can Replace It, It's up to you
github_token                    = ""                    #Replace It
repo_url                        = ""                    #Replace It
directory                       = "" #Replace It (Put Your Github Folder Name Like : (Terraform-AZ-St5)
ssh_dir                         = ""                   #Replace It
openai_api_key                  = ""                   #Replace It
db_name                         = "chats"                                #Replace It
db_user                         = "sdaadmin"                             #Replace It
db_password                     = ""                                     #Replace It
db_port                         = "5432"                                 #Don't Touch it
chromadb_host                   = "127.0.0.1"                            #Don't Touch it
chromadb_port                   = "8000"                                 #Don't Touch it
public_ip_name_appgw            = "st6.1-sda-public-ip-appgw"            #You Can Replace It, It's up to you
subnet_name_appgw               = "AppGatewaySubnet"                     #You Can Replace It, It's up to you
key_vault_name                  = "st6-5-sda-key-vult"                   #You Can Replace It, It's up to you
